server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:sqlite:chat.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: chat-service
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

intent:
  service:
    url: http://localhost:8081

api:
  service:
    url: http://localhost:8082

conversation:
  service:
    url: http://localhost:8083

logging:
  level:
    org.springframework: INFO
    com.example.chat: DEBUG 