server:
  port: 8080

spring:
  application:
    name: chat-service
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: static/**,public/**
    livereload:
      enabled: true
  datasource:
    url: jdbc:sqlite:chat.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: INFO
    com.example.chat: DEBUG

intent:
  service:
    url: http://localhost:8081
api:
  service:
    url: http://localhost:8082
conversation:
  service:
    url: http://localhost:8083 