server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:intent.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: intent-service

logging:
  level:
    org.springframework: INFO
    com.example.intent: DEBUG

# 意图识别配置
intent:
  libraries:
    # 事件库配置文件路径
    personal: classpath:intents/personal_event_patterns.md
    bank: classpath:intents/bank_event_patterns.md
    standard: classpath:intents/standard_event_patterns.md
  # 启用多级解析
  multi-level-parsing: true 